Refactoring

diff --git a/tools/bwa/Index b/tools/bwa/Index
--- a/tools/bwa/Index
+++ b/tools/bwa/Index
@@ -38,6 +38,7 @@ source_version=$2
 tool_version=$5
 
 tool_index_base=$INDEX_BASE/$tool_version
+tool_exec=$PACKAGE_INSTALL_BASE/$tool_version/bwa
 index_dir=$tool_index_base/$source_version/$organism-$dataset
 datasets_fasta_dir=$FASTA_BASE/$source_version/$organism-$dataset
 
@@ -59,17 +60,22 @@ then
    echo "ERROR: directory $datasets_fasta_dir does not exists" | tee -a $log
    exit 1
 fi
-
+if [ ! -f $tool_exec ]
+then
+   echo "ERROR: $tool_exec executable missing" | tee -a $log
+   exit 1
+fi
 #
 # Create index directory if not exists
 #
 [ ! -d $index_dir ] && mkdir -p $index_dir
-if [ -d $index_dir ]
+if [ ! -d $index_dir ]
 then
    echo "ERROR: Failed to create $index_dir"
    exit 1
 fi
 echo "Tool-version: $tool_version" | tee -a $log
+echo "Path to tool exec : $tool_exec" | tee -a $log
 echo "Source-version: $source_version" | tee -a $log
 echo "Organism: $organism" | tee -a $log
 echo "Dataset: $dataset" | tee -a $log
@@ -77,6 +83,8 @@ echo "Indexes Directory: $index_dir" | tee -a $log
 echo "Dataset Directory: $datasets_fasta_dir" | tee -a $log
 source ./$source_config
 file_pattern=""
+genome_file=""
+bwa_algorithm=""
 case "$dataset" in
 "cdna")
     file_pattern=${cdna}
@@ -92,12 +100,29 @@ case "$dataset" in
     ;;
 
 "dna")
-    file_pattern=${dna}
+    file_pattern=${genome}
+    genome_file=$organism${genome}
+    bwa_algorithm=${ALGO_GENOME}
     ;;
 *)
     ;;
 esac
-echo "Dataset File pattern: $file_pattern" | tee -a $log
 
-echo "Program Complete"
+FASTA_FILES="$genome_file"
+[ "$dataset" != "dna" ] && FASTA_FILES=`ls $datasets_fasta_dir | grep $file_pattern`
+
+echo "Dataset File pattern: $file_pattern" | tee -a $log
+# run index command
+cd $index_dir
+file_prefix="-p $tool_version.$source_version.$organism-$dataset"
+echo "Running indexes from `pwd`" | tee -a $log
+for target_file  in $FASTA_FILES
+do 
+    file_prefix="-p $tool_version.$source_version.$target_file"
+    index_cmd="$tool_exec index $file_prefix $bwa_algorithm $datasets_fasta_dir/$target_file"
+    echo "Dataset file: $datasets_fasta_dir/$target_file" | tee -a $log
+    echo "Cmd: $index_cmd" | tee -a $log
+    $index_cmd 2>&1 | tee -a $log
+done
+echo "Program Complete" | tee -a $log
 exit 0
