Added index file prefix as input

diff --git a/tools/bwa/Index b/tools/bwa/Index
--- a/tools/bwa/Index
+++ b/tools/bwa/Index
@@ -9,35 +9,53 @@
 # 2) source_version
 # 3) organism
 # 4) dataset_name
-# 5) bwa version <v0.7.16 | v0.7.17> default current verion
+# 5) tool name
+# 5) tool version <v0.7.16 | v0.7.17> default current verion
 #
 
 SCRIPT_NAME=`basename $0`
 cd `dirname $0`
 echo "Running script from `pwd`"
 
-if [ $# -lt 6 ]
+if [ $# -lt 5 ]
 then 
-  echo "Usage: ./$SCRIPT_NAME  source source-version organism dataset tool-version tool_name"
-  echo "Example: ./$SCRIPT_NAME ensembl ensembl-91 danio_rerio cdna bwa-v0.7.16 bwa"
+  echo "Usage: ./$SCRIPT_NAME  source source-version organism dataset tool_name [tool-version]"
+  echo "Example: ./$SCRIPT_NAME ensembl ensembl-91 danio_rerio cdna bwa [bwa-v0.7.17]"
+  echo "The default tool-version is the current version of the tool"
   exit 1
 fi
 #Check that bwa.cfg exists 
-tool_name=$6
+tool_name=$5
+tool_config=$tool_name.cfg
 
-if [ ! -f bwa.cfg ]
+if [ ! -f $tool_config ]
 then
   echo "ERROR: bwa.cfg file missing from `pwd`"
   exit 1
 fi
 
-source ./bwa.cfg
+source ./$tool_config
 
 organism=$3
 dataset=$4
 data_source=$1
 source_version=$2
-tool_version=$5
+tool_version=$TOOL_VERSION
+index_file_prefix=""
+
+if [ ! -f $REFERENCE_FILE ] 
+then
+   echo "ERROR: $REFERENCE_FILE missing on `uname -n` under `pwd`"
+   exit 1
+fi
+for line in  `cat $REFERENCE_FILE | grep $data_source | grep $dataset`
+do
+       IFS=', ' read -r -a fields <<< "$line"
+       [ "${fields[3]}" = $dataset ] && index_file_prefix=${fields[5]}
+done
+
+[ $# -gt 5 ] && tool_version=$6
+[ $# -gt 6 ] && index_file_prefix=$7
 
 tool_index_base=$INDEX_BASE/$tool_version
 tool_exec=$PACKAGE_INSTALL_BASE/$tool_version/$TOOL_INDEX_EXEC
@@ -82,6 +100,7 @@ echo "Source-version: $source_version" | tee -a $log
 echo "Organism: $organism" | tee -a $log
 echo "Dataset: $dataset" | tee -a $log
 echo "Indexes Directory: $index_dir" | tee -a $log
+echo "Indexes File Prefix: $index_file_prefix" | tee -a $log
 echo "Dataset Directory: $datasets_fasta_dir" | tee -a $log
 source ./$source_config
 file_pattern=""
@@ -100,7 +119,9 @@ case "$dataset" in
 "ncrna")
     file_pattern=${ncrna}
     ;;
-
+"transcriptome_joined")
+    file_pattern=${transcriptome_joined}
+    ;;
 "dna")
     file_pattern=${genome}
     genome_file=$organism${genome}
@@ -119,8 +140,7 @@ cd $index_dir
 echo "Running indexes from `pwd`" | tee -a $log
 for target_file  in $FASTA_FILES
 do 
-    #file_prefix="-p $tool_version.$source_version.$target_file"
-    file_prefix="-p $tool_name-$data_source-$dataset"
+    file_prefix="-p $index_file_prefix"
     index_cmd="$tool_exec index $file_prefix $bwa_algorithm $datasets_fasta_dir/$target_file"
     echo "Dataset file: $datasets_fasta_dir/$target_file" | tee -a $log
     echo "Cmd: $index_cmd" | tee -a $log
