Update Index

diff --git a/tools/kallisto/Index b/tools/kallisto/Index
--- a/tools/kallisto/Index
+++ b/tools/kallisto/Index
@@ -35,12 +35,27 @@ then
 fi
 source ./$tool_config
 
-
 organism=$3
 dataset=$4
 data_source=$1
 source_version=$2
-tool_version=$5
+tool_version=$TOOL_VERSION
+index_file_prefix=""
+this_reference_file="$data_source-reference.csv"
+
+if [ ! -f $this_reference_file ] 
+then
+   echo "ERROR: $this_reference_file missing on `uname -n` under `pwd`"
+   exit 1
+fi
+for line in  `cat $this_reference_file | grep $data_source | grep $dataset`
+do
+       IFS=', ' read -r -a fields <<< "$line"
+       [ "${fields[3]}" = $dataset ] && index_file_prefix=${fields[5]}
+done
+
+[ $# -gt 5 ] && tool_version=$6
+[ $# -gt 6 ] && index_file_prefix=$7
 
 tool_index_base=$INDEX_BASE/$tool_version
 tool_exec=$PACKAGE_INSTALL_BASE/$tool_version/$TOOL_INDEX_EXEC
@@ -50,10 +65,8 @@ datasets_fasta_dir=$FASTA_BASE/$source_version/$organism-$dataset
 source_config=../../data_sources/$data_source.cfg
 
 log=$LOGS_BASE/$SCRIPT_NAME.$source_version.$organism-$dataset.$tool_version.log
-
 rm -rf $log
 touch $log
-
 echo "*************************************************" | tee -a $log
 echo "Generating $tool_version indexes for $source_version $organism's $dataset"  | tee -a $log
 echo "*************************************************" | tee -a $log
@@ -70,6 +83,12 @@ then
    echo "ERROR: $tool_exec executable missing" | tee -a $log
    exit 1
 fi
+#If this dataset has already been indexed continue
+if [ -d $index_dir ]
+then
+   echo "SKIPPING: $index_dir already exists" | tee -a $log
+   exit 0 
+fi
 #
 # Create index directory if not exists
 #
@@ -81,37 +100,18 @@ then
 fi
 echo "Tool-version: $tool_version" | tee -a $log
 echo "Path to tool exec : $tool_exec" | tee -a $log
-echo "Source-version: $source_version" | tee -a $log
+echo "Data Source version: $source_version" | tee -a $log
 echo "Organism: $organism" | tee -a $log
 echo "Dataset: $dataset" | tee -a $log
 echo "Indexes Directory: $index_dir" | tee -a $log
-echo "Dataset Directory: $datasets_fasta_dir" | tee -a $log
+echo "Indexes File Prefix: $index_file_prefix" | tee -a $log
+echo "Input Dataset Directory: $datasets_fasta_dir" | tee -a $log
+
 source ./$source_config
-
 file_pattern=""
-
-case "$dataset" in
-"cdna")
-    file_pattern=${cdna}
-    ;;
-"cds")
-    file_pattern=${cds}
-    ;;    
-"pep")
-    file_pattern=${pep}
-    ;;
-"ncrna")
-    file_pattern=${ncrna}
-    ;;
-
-"dna")
-    file_pattern=${genome}
-    ;;
-*)
-    ;;
-esac
-
+file_pattern=$DATASETS[$dataset]
 FASTA_FILES=`ls $datasets_fasta_dir | grep $file_pattern`
+
 echo "Dataset File pattern: $file_pattern" | tee -a $log
 # run index command
 reference_in=""
