Update Index

diff --git a/tools/hisat2/Index b/tools/hisat2/Index
--- a/tools/hisat2/Index
+++ b/tools/hisat2/Index
@@ -20,7 +20,7 @@ echo "Running script from `pwd`"
 
 if [ $# -lt 5 ]
 then 
-  echo "Usage: ./$SCRIPT_NAME  source source-version organism dataset tool_name [tool-version]"
+  echo "Usage: ./$SCRIPT_NAME  source source-version organism dataset tool_name [tool-version][index_prefix]"
   echo "Example: ./$SCRIPT_NAME ensembl ensembl-91 danio_rerio cdna hisat2 [hisat2-2.1.0][hisat2-ensembl-cdna]"
   echo "The default tool-version is the current version of the tool"
   echo "The default index-prefix is tool_name-data_source_name-dataset"
@@ -29,13 +29,23 @@ fi
 #Check that tool_name.cfg exists 
 tool_name=$5
 tool_config=$tool_name.cfg
-
+##Set global environment variables
+#
+main_config=Configuration.cfg
+##
+if [ ! -f ../../$main_config ]
+then
+  echo "ERROR: ../../$main_config file missing"
+  exit 1 
+fi
+source ./../../$main_config
 if [ ! -f $tool_config ]
 then
   echo "ERROR: $tool_config file missing from `pwd`"
   exit 1
 fi
-
+##Set this tool's specific variables
+#
 source ./$tool_config
 
 organism=$3
@@ -63,19 +73,9 @@ done
 tool_index_base=$INDEX_BASE/$tool_version
 tool_exec=$PACKAGE_INSTALL_BASE/$tool_version/$TOOL_INDEX_EXEC
 index_dir=$tool_index_base/$source_version/$organism-$dataset
-datasets_fasta_dir=$FASTA_BASE/$source_version/$organism-$dataset
+datasets_fasta_dir=$FASTA_FILES_BASE/$source_version/$organism-$dataset
 
 source_config=../../data_sources/$data_source.cfg
-
-log=$LOGS_BASE/$SCRIPT_NAME.$source_version.$organism-$dataset.$tool_version.log
-
-rm -rf $log
-touch $log
-echo "*************************************************" | tee -a $log
-echo "Generating $tool_version indexes for $source_version $organism's $dataset"  | tee -a $log
-echo "*************************************************" | tee -a $log
-echo "Date:`date`" | tee -a $log
-echo "ORGANIZATION:$ORGANIZATION" | tee -a $log 
 
 if [ ! -d $datasets_fasta_dir ]
 then
@@ -91,7 +91,7 @@ fi
 if [ -d $index_dir ]
 then
    echo "SKIPPING: $index_dir already exists" | tee -a $log
-   exit 0 
+   exit 0
 fi
 #
 # Create index directory if not exists
@@ -102,6 +102,16 @@ then
    echo "ERROR: Failed to create $index_dir"
    exit 1
 fi
+
+log=$LOGS_BASE/$SCRIPT_NAME.$source_version.$organism-$dataset.$tool_version.log
+
+rm -rf $log
+touch $log
+echo "*************************************************" | tee -a $log
+echo "Generating $tool_version indexes for $source_version $organism's $dataset"  | tee -a $log
+echo "*************************************************" | tee -a $log
+echo "Date:`date`" | tee -a $log
+echo "ORGANIZATION:$ORGANIZATION" | tee -a $log 
 echo "Tool-version: $tool_version" | tee -a $log
 echo "Path to tool exec : $tool_exec" | tee -a $log
 echo "Data Source version: $source_version" | tee -a $log
@@ -110,13 +120,11 @@ echo "Dataset: $dataset" | tee -a $log
 echo "Indexes Directory: $index_dir" | tee -a $log
 echo "Indexes File Prefix: $index_file_prefix" | tee -a $log
 echo "Input Dataset Directory: $datasets_fasta_dir" | tee -a $log
-
 source ./$source_config
 
 file_pattern=""
 file_pattern=$DATASETS[$dataset]
 FASTA_FILES=`ls $datasets_fasta_dir | grep $file_pattern`
-
 echo "Dataset File pattern: $file_pattern" | tee -a $log
 # run index command
 reference_in=""
