Added pipeline-runs

diff --git a/tools/rsem/Index-tx2genemap b/tools/rsem/Index-tx2genemap
--- a/tools/rsem/Index-tx2genemap
+++ b/tools/rsem/Index-tx2genemap
@@ -2,9 +2,13 @@
 
 #
 #A script to pre-index a given dataset 
-# Without using the isoform or gtf options
+# in RSEM using transcript-to-gene-map option
 # Example:
-# rsem-prepare-reference   path2/mm9.fasta  reference_name
+# rsem-prepare-reference --transcript-to-gene-map mapping.txt \
+#                        --polyA
+#                        mm9.fasta \
+#                        mouse_125
+
 #
 
 # Input:
@@ -25,10 +29,11 @@ WORKING_DIR=`pwd`
 if [ $# -lt 6 ]
 then 
   echo "Usage: ./$SCRIPT_NAME dataset-version  organism dataset \
-        path2/reference_fasta_file index_dir index_prefix [polyA]"
-  echo "Example: ./$SCRIPT_NAME ensembl-94  mus_musculus cdna \
- /data/scratch/ensembl-94/mus_musculus-cdna/Mus_musculus.GRCm38.cdna.all.fa \
- /data/transformed/RSEM-v1.3.0/ensembl-94/mus_musculus-cdna transcriptome
+        path2/trans2gene_map_file path2/reference_fasta_file index_dir/index_prefix [polyA]"
+  echo "Example: ./$SCRIPT_NAME axolotl-omics-transcriptome-Am_3.4  axolotl transcriptome \
+ /data/scratch/axolotl-omics-transcriptome-Am_3.4/annotations/axolotl-transcriptome.known_isoforms.txt \
+ /data/scratch/axolotl-omics-transcriptome-Am_3.4/axolotl-transcriptome/Am_34.final.fa \
+ /data/transformed/RSEM-v1.3.0/axolotl-omics-transcriptome-Am_3.4/axolotl-transcriptome axolotl-omics-transcriptome
         "
   exit 1
 fi
@@ -55,15 +60,27 @@ source ./$tool_config
 source_version=$1
 organism=$2
 dataset=$3
-reference_file=$4
-index_dir=$5
-index_file_prefix=$6
+transcript_to_gene_map_file=$4
+reference_file=$5
+index_dir=$6
+index_file_prefix=$7
 polyA=""
 tool_version=$TOOL_VERSION
-[ $# -gt 6 ] && polyA="--polyA"
+[ $# -gt 7 ] && polyA="--polyA"
 
 tool_index_base=$INDEX_BASE/$tool_version
 tool_exec=$PACKAGE_INSTALL_BASE/$tool_version/$TOOL_INDEX_EXEC
+if [ ! -f $transcript_to_gene_map_file ]
+then
+   echo "ERROR:  transcript-to-gene-map file is not a valid file."
+   exit 1
+fi
+if [ ! -f $reference_file ]
+then
+   echo "ERROR:  The reference fasta file is not a valid file."
+   exit 1
+fi
+
 if [ ! -f $tool_exec ]
 then
    echo "ERROR: $tool_exec executable missing" | tee -a $log
@@ -105,10 +122,11 @@ echo "Dataset: $dataset" | tee -a $log
 echo "Indexes Directory: $index_dir" | tee -a $log
 echo "Indexes File Prefix: $index_file_prefix" | tee -a $log
 echo "Refence Data Source version: $source_version" | tee -a $log
-echo "Transcript gtf Input file: $transcript_gtf_file" | tee -a $log
+echo "Transcript-togene-map Input file: $transcript_to_gene_map_file" | tee -a $log
 echo "Reference fasta file: $reference_file" | tee -a $log
 
-index_cmd="$tool_exec $polyA $reference_file $index_dir/$index_file_prefix"
+index_cmd="$tool_exec --transcript-to-gene-map $transcript_to_gene_map_file $polyA \
+    $reference_file $index_dir/$index_file_prefix"
 echo " -------------------------- " | tee -a $log
 echo " " | tee -a $log
 echo "Indexer Cmd: $index_cmd" | tee -a $log
