Update Index

diff --git a/tools/bowtie2/Index b/tools/bowtie2/Index
--- a/tools/bowtie2/Index
+++ b/tools/bowtie2/Index
@@ -17,28 +17,47 @@ SCRIPT_NAME=`basename $0`
 cd `dirname $0`
 echo "Running script from `pwd`"
 
-if [ $# -lt 6 ]
+if [ $# -lt 5 ]
 then 
-  echo "Usage: ./$SCRIPT_NAME  source source-version organism dataset tool-version tool_name"
-  echo "Example: ./$SCRIPT_NAME ensembl ensembl-91 danio_rerio cdna bowtie2-v2.3.3.1 bowtie2"
+  echo "Usage: ./$SCRIPT_NAME  source source-version organism dataset tool_name [tool-version]"
+  echo "Example: ./$SCRIPT_NAME ensembl ensembl-91 danio_rerio cdna bowtie2 [bowtie2-v2.3.4]"
+  echo "The default tool-version is the current version of the tool"
   exit 1
 fi
 #Check that bwa.cfg exists 
-tool_name=$6
+tool_name=$5
+tool_config=$tool_name.cfg
 
-if [ ! -f $tool_name.cfg ]
+if [ ! -f $tool_config ]
 then
   echo "ERROR: bwa.cfg file missing from `pwd`"
   exit 1
 fi
 
-source ./$tool_name.cfg
+source ./$tool_config
+
 
 organism=$3
 dataset=$4
 data_source=$1
 source_version=$2
-tool_version=$5
+tool_version=$TOOL_VERSION
+index_file_prefix=""
+this_reference_file="$data_source-reference.csv"
+
+if [ ! -f $this_reference_file ] 
+then
+   echo "ERROR: $this_reference_file missing on `uname -n` under `pwd`"
+   exit 1
+fi
+for line in  `cat $this_reference_file | grep $data_source | grep $dataset`
+do
+       IFS=', ' read -r -a fields <<< "$line"
+       [ "${fields[3]}" = $dataset ] && index_file_prefix=${fields[5]}
+done
+
+[ $# -gt 5 ] && tool_version=$6
+[ $# -gt 6 ] && index_file_prefix=$7
 
 tool_index_base=$INDEX_BASE/$tool_version
 tool_exec=$PACKAGE_INSTALL_BASE/$tool_version/$TOOL_INDEX_EXEC
@@ -51,6 +70,7 @@ log=$LOGS_BASE/$SCRIPT_NAME.$source_version.$organism-$dataset.$tool_version.log
 
 rm -rf $log
 touch $log
+
 
 echo "*************************************************" | tee -a $log
 echo "Generating $tool_version indexes for $source_version $organism's $dataset"  | tee -a $log
