Update Index

diff --git a/tools/bowtie2/Index b/tools/bowtie2/Index
--- a/tools/bowtie2/Index
+++ b/tools/bowtie2/Index
@@ -20,7 +20,7 @@ echo "Running script from `pwd`"
 
 if [ $# -lt 5 ]
 then 
-  echo "Usage: ./$SCRIPT_NAME  source source-version organism dataset tool_name [tool-version]"
+  echo "Usage: ./$SCRIPT_NAME  source source-version organism dataset tool_name [tool-version][index_prefix]"
   echo "Example: ./$SCRIPT_NAME ensembl ensembl-91 danio_rerio cdna bowtie2 [bowtie2-v2.3.4][bowtie2-ensembl-cdna]"
   echo "The default tool-version is the current version of the tool"
   echo "The default index-prefix is tool_name-data_source_name-dataset"
@@ -29,14 +29,22 @@ fi
 #Check that tool_name.cfg exists 
 tool_name=$5
 tool_config=$tool_name.cfg
-
+##Set global environment variables
+#
+main_config=Configuration.cfg
+##
+if [ ! -f ../../$main_config ]
+then
+  echo "ERROR: ../../$main_config file missing"
+  exit 1 
+fi
+source ./../../$main_config
 if [ ! -f $tool_config ]
 then
   echo "ERROR: $tool_config file missing from `pwd`"
   exit 1
 fi
 source ./$tool_config
-
 
 organism=$3
 dataset=$4
@@ -63,21 +71,9 @@ done
 tool_index_base=$INDEX_BASE/$tool_version
 tool_exec=$PACKAGE_INSTALL_BASE/$tool_version/$TOOL_INDEX_EXEC
 index_dir=$tool_index_base/$source_version/$organism-$dataset
-datasets_fasta_dir=$FASTA_BASE/$source_version/$organism-$dataset
+datasets_fasta_dir=$FASTA_FILES_BASE/$source_version/$organism-$dataset
 
 source_config=../../data_sources/$data_source.cfg
-
-log=$LOGS_BASE/$SCRIPT_NAME.$source_version.$organism-$dataset.$tool_version.log
-
-rm -rf $log
-touch $log
-
-echo "*************************************************" | tee -a $log
-echo "Generating $tool_version indexes for $source_version $organism's $dataset"  | tee -a $log
-echo "*************************************************" | tee -a $log
-echo "Date:`date`" | tee -a $log
-echo "ORGANIZATION:$ORGANIZATION" | tee -a $log 
-
 if [ ! -d $datasets_fasta_dir ]
 then
    echo "ERROR: directory $datasets_fasta_dir does not exists" | tee -a $log
@@ -92,7 +88,7 @@ fi
 if [ -d $index_dir ]
 then
    echo "SKIPPING: $index_dir already exists" | tee -a $log
-   exit 0 
+   exit 0
 fi
 #
 # Create index directory if not exists
@@ -104,6 +100,16 @@ then
    exit 1
 fi
 
+log=$LOGS_BASE/$SCRIPT_NAME.$source_version.$organism-$dataset.$tool_version.log
+
+rm -rf $log
+touch $log
+
+echo "*************************************************" | tee -a $log
+echo "Generating $tool_version indexes for $source_version $organism's $dataset"  | tee -a $log
+echo "*************************************************" | tee -a $log
+echo "Date:`date`" | tee -a $log
+echo "ORGANIZATION:$ORGANIZATION" | tee -a $log 
 echo "Tool-version: $tool_version" | tee -a $log
 echo "Path to tool exec : $tool_exec" | tee -a $log
 echo "Data Source version: $source_version" | tee -a $log
